-- From: https://asn1.io/asn1playground/Default.aspx
--<ASN1.HugeInteger World-Schema.Rocket.range>--
World-Schema DEFINITIONS AUTOMATIC TAGS ::= 
BEGIN
  Rocket ::= SEQUENCE       
  {
     range     INTEGER, -- huge (see a special directive above)
     name      OCTET STRING,
     ident     OBJECT IDENTIFIER, 
     speed     CHOICE
     { 
        mph    INTEGER,  
        kmph   INTEGER  
     }  OPTIONAL, 
     payload   SEQUENCE OF INTEGER
  }                                                     
END